import Link from 'next/link';

export default function Terms() {
  return (
    <div className="min-h-screen bg-neutral-950 text-white flex flex-col">
      {/* Navigation */}
      <nav className="flex items-center justify-between px-6 py-4 border-b border-white/5 relative z-20 bg-neutral-950/80 backdrop-blur-xl">
        <Link href="/" className="text-xl font-bold tracking-tighter hover:text-indigo-400 transition-colors">Kudos</Link>
        <div className="flex gap-6 text-sm font-medium text-neutral-400">
          <Link href="/about" className="hover:text-white transition-colors">About</Link>
          <Link href="/features" className="hover:text-white transition-colors">Features</Link>
          <Link href="/pricing" className="hover:text-white transition-colors">Pricing</Link>
          <Link href="/contact" className="hover:text-white transition-colors">Contact</Link>
        </div>
        <div className="flex gap-4">
          <Link href="/login" className="px-4 py-2 text-sm font-medium hover:text-indigo-400 transition-colors">Log In</Link>
          <Link href="/signup" className="px-4 py-2 text-sm font-medium bg-white text-black rounded-full hover:bg-neutral-200 transition-colors">Sign Up</Link>
        </div>
      </nav>

      {/* Content */}
      <main className="flex-1 max-w-4xl w-full mx-auto px-6 py-24">
        <h1 className="text-5xl font-bold tracking-tight mb-8">Terms of Service</h1>
        <p className="text-neutral-400 mb-8">Last Updated: July 22, 2026</p>
        
        <div className="space-y-8 text-lg text-neutral-300 leading-relaxed">
          <section>
            <h2 className="text-2xl font-bold mb-4 text-white">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Kudos, you agree to be bound by these Terms of Service. If you do not agree, you may not use the platform. You must be at least 18 years old to use Kudos.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-white">2. Description of Service</h2>
            <p>
              Kudos provides an AI companion interface designed to facilitate self-reflection and connection with other human users. We do not guarantee any specific matches, relationships, or business outcomes resulting from the use of our service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-white">3. User Conduct</h2>
            <p className="mb-4">
              You agree not to use Kudos to:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Harass, abuse, or harm another person.</li>
              <li>Impersonate any person or entity.</li>
              <li>Send spam or commercial solicitations.</li>
              <li>Use the AI to generate illegal, harmful, or highly offensive content.</li>
            </ul>
            <p className="mt-4">
              Violation of these rules may result in immediate account termination without refund.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-white">4. Artificial Intelligence Disclaimer</h2>
            <p>
              Your AI companion's responses are generated by Large Language Models (LLMs). These models may sometimes produce inaccurate, biased, or nonsensical information. You should not rely on the AI for professional, legal, medical, or financial advice.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-white">5. Payments and Subscriptions</h2>
            <p>
              While Kudos may offer free access during early phases, certain features may require a paid subscription. All fees are clearly stated at checkout. By providing payment information, you authorize us to charge you for the selected plan.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-white">6. Limitation of Liability</h2>
            <p>
              Kudos is provided "as is". We are not liable for any damages arising from your use of the platform, the AI's responses, or your interactions with other users.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-white">7. Governing Law</h2>
            <p>
              These Terms shall be governed by the laws of India, without regard to its conflict of law provisions.
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
