import Link from 'next/link';

export default function Privacy() {
  return (
    <div className="min-h-screen bg-neutral-950 text-white flex flex-col">
      {/* Navigation */}
      <nav className="flex items-center justify-between px-6 py-4 border-b border-white/5 relative z-20 bg-neutral-950/80 backdrop-blur-xl">
        <Link href="/" className="text-xl font-bold tracking-tighter hover:text-indigo-400 transition-colors">Kudos</Link>
        <div className="flex gap-6 text-sm font-medium text-neutral-400">
          <Link href="/about" className="hover:text-white transition-colors">About</Link>
          <Link href="/features" className="hover:text-white transition-colors">Features</Link>
          <Link href="/pricing" className="hover:text-white transition-colors">Pricing</Link>
          <Link href="/contact" className="hover:text-white transition-colors">Contact</Link>
        </div>
        <div className="flex gap-4">
          <Link href="/login" className="px-4 py-2 text-sm font-medium hover:text-indigo-400 transition-colors">Log In</Link>
          <Link href="/signup" className="px-4 py-2 text-sm font-medium bg-white text-black rounded-full hover:bg-neutral-200 transition-colors">Sign Up</Link>
        </div>
      </nav>

      {/* Content */}
      <main className="flex-1 max-w-4xl w-full mx-auto px-6 py-24">
        <h1 className="text-5xl font-bold tracking-tight mb-8">Privacy Policy</h1>
        <p className="text-neutral-400 mb-8">Last Updated: July 22, 2026</p>
        
        <div className="space-y-8 text-lg text-neutral-300 leading-relaxed">
          <section>
            <h2 className="text-2xl font-bold mb-4 text-white">1. Information We Collect</h2>
            <p className="mb-4">
              When you use Kudos, we collect the following types of information:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Account Information:</strong> Your name, email address, and profile details (role, tagline, bio, location).</li>
              <li><strong>Conversation Data:</strong> The messages you send to your AI companion.</li>
              <li><strong>Personality & Preferences:</strong> Traits and insights generated by the AI to help match you with others.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-white">2. How We Store Your Data</h2>
            <p>
              Your personal data, including your profile and chat history, is securely stored using Google Cloud's Firebase infrastructure (Firestore). We implement strict security rules to ensure that your private data is only accessible by you and the AI systems necessary to power the platform.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-white">3. How We Process Data (AI Integration)</h2>
            <p>
              To provide the AI companion experience, your conversation data is processed using third-party Large Language Models (LLMs) hosted by <strong>Groq</strong>.
            </p>
            <ul className="list-disc pl-6 mt-4 space-y-2">
              <li>We do <strong>not</strong> use your private conversations to train public models.</li>
              <li>Data sent to Groq is solely for the purpose of generating responses and maintaining your companion's memory.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-white">4. Data Sharing & Matchmaking</h2>
            <p>
              Kudos is designed to introduce you to other humans. When you opt-in to matchmaking or complete onboarding, a public version of your profile (Name, Role, Tagline, Bio, Location, and Shared Traits) becomes visible to potential matches. Your private chat logs with the AI are <strong>never</strong> shared with other users.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-white">5. Your Rights</h2>
            <p>
              You have the right to access, update, or delete your personal data at any time. You can edit your profile through the dashboard. If you wish to permanently delete your account and all associated data, please contact us.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-white">6. Contact Us</h2>
            <p>
              If you have any questions about this Privacy Policy, please contact us at: <strong>support@kudos.app</strong>.
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
